//adding animals comma seperated into an associative array.
export const names = [
    'Monkey',
    'Panda',
    'Shark',
    'Zebra',
    'Gorilla',
    'Walrus',
    'Leopard',
    'Wolf',
    'Antelope',
    'Eagle',
    'Jellyfish',
    'Crab',
    'Giraffe',
    'Woodpecker',
    'Camel',
    'Starfish',
    'Koala',
    'Alligator',
    'Owl',
    'Tiger',
    'Bear',
    'Whale',
    'Coyote',
    'Chimpanzee',
    'Raccoon',
    'Lion',
    'Wolf',
    'Crocodile',
    'Dolphin',
    'Elephant',
    'Squirrel',
    'Snake',
    'Kangaroo',
    'Hippopotamus',
    'Elk',
    'Rabbit',
    'Fox',
    'Gorilla',
    'Bat',
    'Hare',
    'Toad',
    'Frog',
    'Deer',
    'Rat',
    'Badger',
    'Lizard',
    'Mole',
    'Hedgehog',
    'Otter'
   
]

export default names;
